[METADATA]
version = 0.1
description = "A sample prompt for RadPrompter"

[PROMPTS]

system_prompt = "You are a helpful assistant that has 20 years of experience in reading radiology reports and extracting data elements."

user_prompt_intro = "{{intro_prompt}}\n"

user_prompt_no_cot = """
I want you to extract the following data element from the report: 
{{variable_name}}:
{{hint}}

Provide a single answer:

"""

[CONSTRUCTOR]
system = "rdp(system_prompt)"
user = [
"rdp(user_prompt_intro + user_prompt_no_cot)"
]

[SCHEMAS]
[SCHEMAS.PulmonaryEmbolism]
variable_name = "Pulmonary Embolism"
intro_prompt = """
Carefully review the provided chest CT report (in the <report> tag). Ensure that each data element is accurately captured.

Here is the report:
<report>
{{report}}
</report>

Please pay attention to the following details:
- Your attention to detail is crucial for maintaining the integrity of the medical records. 
- You should not confabulate information, and if something is not mentioned, you should assume that it is `Absent` unless otherwise stated.
- The report may contain additional information that is not relevant to the requested data elements. Please ignore that information.
- We are interested at findings at the time of scan, not the previous ones, so only consider the impression and findings sections of the report.
- Do not print anything else other than the provided output format.
"""
type = "select"
options = ["Present", "Absent"]
show_options_in_hint = true
hint = """
Indicate `Present` if the report explicitly mentions the patient has pulmonary embolism in their CT scan. 
Indicate `Absent` if pulmonary embolism is not seen or if a previously observed pulmonary embolism is mentioned as resolved.
"""

[SCHEMAS.PatientAge]
variable_name = "Patient Age"
intro_prompt = ""
type = "int"
show_options_in_hint = false
hint = """
Extract the patient's age in years from the report. If age is not explicitly mentioned, respond with -1.
Provide only the numerical value (e.g., 65).
"""

[SCHEMAS.LesionSize]
variable_name = "Largest Lesion Size"
intro_prompt = ""
type = "float"
show_options_in_hint = false
hint = """
Extract the size of the largest lesion mentioned in the report in centimeters.
If multiple dimensions are given, use the largest dimension.
If no lesion size is mentioned, respond with -1.0.
Provide only the numerical value (e.g., 2.5).
"""

[SCHEMAS.ClinicalImpression]
variable_name = "Clinical Impression"
intro_prompt = ""
type = "string"
show_options_in_hint = false
hint = """
Extract the main clinical impression or conclusion from the report.
Provide the exact text from the impression section, or summarize the key findings if no explicit impression is stated.
If no clear impression is available, respond with "Not specified".
"""

[SCHEMAS.NumberOfEmboli]
variable_name = "Number of Pulmonary Emboli"
intro_prompt = ""
type = "int"
show_options_in_hint = false
hint = """
Count the number of pulmonary emboli explicitly mentioned in the report.
If the report mentions "multiple" without a specific count, respond with -1.
If no emboli are present, respond with 0.
Provide only the numerical count.
"""

[SCHEMAS.Left]
variable_name = "Left-sided Pulmonary Embolism"
intro_prompt = ""
type = "select"
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report explicitly mentions the patient has a left-sided pulmonary embolism in their CT scan. 
Indicate `Yes` if the report explicitly mentions the patient has a bilateral pulmonary embolism in their CT scan or if patient has both left and right sided pulmonary embolism.
Indicate `No` if the report doesn't explicitly mentions the patient has a left-sided or bilateral pulmonary embolism in their CT scan. 
"""

[SCHEMAS.Right]
variable_name = "Right-sided Pulmonary Embolism"
type = "select"
intro_prompt = ""
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report explicitly mentions the patient has a right-sided pulmonary embolism in their CT scan. 
Indicate `Yes` if the report explicitly mentions the patient has a bilateral pulmonary embolism in their CT scan or if patient has both left and right sided pulmonary embolism.
Indicate `No` if the report doesn't explicitly mentions the patient has a right-sided or bilateral pulmonary embolism in their CT scan. 
"""

[SCHEMAS.Acute]
variable_name = "Acute Pulmonary Embolism"
type = "select"
intro_prompt = ""
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report explicitly mentions the patient has an acute pulmonary embolism in their CT scan. 
Indicate `No` if the report doesn't explicitly mentions the patient has an acute pulmonary embolism in their CT scan. 
"""

[SCHEMAS.Chronic]
variable_name = "Chronic Pulmonary Embolism"
type = "select"
intro_prompt = ""
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report explicitly mentions the patient has an chronic pulmonary embolism in their CT scan. 
Indicate `No` if the report doesn't explicitly mentions the patient has an chronic pulmonary embolism in their CT scan. 
"""

[SCHEMAS.RightHeartStrain]
variable_name = "Right Heart Strain"
type = "select"
intro_prompt = ""
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report does explicitly mentions that the patient has a right heart strain in their CT scan. 
Indicate `No` if the report doesn't explicitly mentions that the patient has a right heart strain in their CT scan. 
"""

[SCHEMAS.PulmonaryArteryHypertension]
variable_name = "Pulmonary Artery Hypertension"
type = "select"
intro_prompt = ""
options = ["Yes", "No"]
show_options_in_hint = true
hint = """
Indicate `Yes` if the report does explicitly mentions that the patient has a pulmonary artery hypertension in their CT scan. 
Indicate `No` if the report doesn't explicitly mentions that the patient has a pulmonary artery hypertension in their CT scan. 
"""
