[METADATA]

version = 0.1
description = "A sample prompt for RadPrompter"

[PROMPTS]

system_prompt = "You are a helpful assistant that has 20 years of experience in reading radiology reports and extracting data elements."

user_prompt_intro = """
Carefully review the provided chest CT report (in the <report> tag). Ensure that each data element is accurately captured.

Here is the report:
<report>
{{report}}
</report>

Please pay attention to the following details:
- Your attention to detail is crucial for maintaining the integrity of the medical records. 
- You should not confabulate information, and if something is not mentioned, you should assume that it is `Absent` unless otherwise stated.
- The report may contain additional information that is not relevant to the requested data elements. Please ignore that information.
- We are interested at findings at the time of scan, not the previous ones, so only consider the impression and findings sections of the report.
- Do not print anything else other than the provided output format.
"""

user_prompt_no_cot = """
I want you to extract the following data element from the report: 
Pulmonary Embolism:
Indicate `Present` if the report explicitly mentions the patient has pulmonary embolism in their CT scan. 
Indicate `Absent` if pulmonary embolism is not seen or if a previously observed pulmonary embolism is mentioned as resolved.

Your final answer elements in a valid JSON format and is between <json> and </json> tags:

<json>
{
  "Pulmonary Embolism": "answer"
}
</json>
"""

assistant_response_template = """{
"Pulmonary Embolism" : """

[CONSTRUCTOR]
system = "rdp(system_prompt)"
user = "rdp(user_prompt_intro + user_prompt_no_cot)"
response_templates = "rdp(assistant_response_template)"
stop_tags = "</json>"